### ISSUE TITLE
Unable to issue certificates with Subordinate Cert Authority

### ISSUE THREAD

**Issue by ae07177** [OwnCA/ownca#68]
Hi Team,
I see in the documentation that we cannot create cert for subordinate ca.
How do I get this SubOrdinate CA crt file signed and generated. Could you please provide an example.

ownca.exceptions.OwnCAIntermediate: Intermediate Certificate Authority has not a signed certificate file in CA Storage

**Comment by ae07177** [comment]
Related functions in code

def issue_cert_with_sub(sca):
  client_domain = input("Enter Your Domain:")
  cert_path = './Root_Sub_CA/certs/' + client_domain + '/'
  if os.path.isdir(cert_path):
    print("Cert for the domain: ", client_domain, " is already present. Please try with new name or delete existing")
  else:
    client_dns_names = input("Enter Your DNS Domains Seperated by Comma:")
    client_ca = sca.issue_certificate(client_domain, dns_names=[ client_dns_names ] )

def create_sub_ca():
  scaname = input("Enter the Name for SubCA:")
  sub_ca = CertificateAuthority(ca_storage='./Root_Sub_CA', common_name=scaname, intermediate=True)
  return sub_ca

Error during execution
JARRIETA-L:CA ashivaramakrishnan$ python3 ca.py 
Enter the Name for RootCA:AS
Enter the Name for SubCA:AR
Enter Your Domain:abc.com   
Enter Your DNS Domains Seperated by Comma:abc.com
Traceback (most recent call last):
  File "/Users/ashivaramakrishnan/lambda/acm/CA/ca.py", line 38, in <module>
    issue_cert_with_sub(sca)
  File "/Users/ashivaramakrishnan/lambda/acm/CA/ca.py", line 27, in issue_cert_with_sub
    client_ca = sca.issue_certificate(client_domain, dns_names=[ client_dns_names ] )
  File "/usr/local/lib/python3.9/site-packages/ownca/ownca.py", line 980, in issue_certificate
    self.cert,
  File "/usr/local/lib/python3.9/site-packages/ownca/ownca.py", line 618, in cert
    raise OwnCAIntermediate(
**_ownca.exceptions.OwnCAIntermediate: Intermediate Certificate Authority has not a signed certificate file in CA Storage_**
JARRIETA-L:CA ashivaramakrishnan$

**Comment by ae07177** [comment]
Hello. Any update on this?

**Comment by ae07177** [comment]
Never mind , I've figured it out :)
