### ISSUE TITLE
Make docs is failing in GA

### ISSUE THREAD

**Issue by kairoaraujo** [OwnCA/ownca#73]
The make docs tests in GA are constantly failing. 
Example: https://github.com/OwnCA/ownca/runs/7416704390?check_suite_focus=true

```shell
Run make docs
[7](https://github.com/OwnCA/ownca/runs/7416704482?check_suite_focus=true#step:8:8)
sphinx-apidoc -o  docs/source/ ownca/
[8](https://github.com/OwnCA/ownca/runs/7416704482?check_suite_focus=true#step:8:9)
Traceback (most recent call last):
[9](https://github.com/OwnCA/ownca/runs/7416704482?check_suite_focus=true#step:8:10)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/bin/sphinx-apidoc", line 5, in <module>
[10](https://github.com/OwnCA/ownca/runs/7416704482?check_suite_focus=true#step:8:11)
    from sphinx.ext.apidoc import main
[11](https://github.com/OwnCA/ownca/runs/7416704482?check_suite_focus=true#step:8:12)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/sphinx/ext/apidoc.py", line 29, in <module>
[12](https://github.com/OwnCA/ownca/runs/7416704482?check_suite_focus=true#step:8:13)
    from sphinx.cmd.quickstart import EXTENSIONS
[13](https://github.com/OwnCA/ownca/runs/7416704482?check_suite_focus=true#step:8:14)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/sphinx/cmd/quickstart.py", line 44, in <module>
[14](https://github.com/OwnCA/ownca/runs/7416704482?check_suite_focus=true#step:8:15)
    from sphinx.util.template import SphinxRenderer
[15](https://github.com/OwnCA/ownca/runs/7416704482?check_suite_focus=true#step:8:16)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/sphinx/util/template.py", line 18, in <module>
[16](https://github.com/OwnCA/ownca/runs/7416704482?check_suite_focus=true#step:8:17)
    from sphinx.jinja2glue import SphinxFileSystemLoader
[17](https://github.com/OwnCA/ownca/runs/7416704482?check_suite_focus=true#step:8:18)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/sphinx/jinja2glue.py", line 15, in <module>
[18](https://github.com/OwnCA/ownca/runs/7416704482?check_suite_focus=true#step:8:19)
    from jinja2 import FileSystemLoader, BaseLoader, TemplateNotFound, \
[19](https://github.com/OwnCA/ownca/runs/7416704482?check_suite_focus=true#step:8:20)
ImportError: cannot import name 'contextfunction' from 'jinja2' (/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/jinja2/__init__.py)
[20](https://github.com/OwnCA/ownca/runs/7416704482?check_suite_focus=true#step:8:21)
make: *** [Makefile:43: docs] Error 1
[21](https://github.com/OwnCA/ownca/runs/7416704482?check_suite_focus=true#step:8:22)
Error: Process completed with exit code 2.

```

**Comment by KAUTH** [comment]
This seems to be a dependency problem between sphinx and jinja2 (see https://github.com/pallets/jinja/pull/1544 and https://stackoverflow.com/a/71634495); we are using jinja2 3.0.1.
An upgrade of sphinx-rtd-theme should fix this. We need to update the docs/requirements.txt file.

Do you know how we could easily generate the requirements.txt file for the docs? For the others we can pipenv install -d and then pipenv lock -r > requirements.txt or pipenv lock -r --dev > dev-requirements.txt.
What I did is installed sphinx in a virtual env (pipenv install sphinx) and then created the requirements with pipenv lock -r (basically these packages and their dependencies https://github.com/sphinx-doc/sphinx/blob/5.x/setup.py#L14).

I'm going to send a PR to test it out.
